name: deploy-api
on:
  push:
    branches:
        - main
        - api/**
  pull_request:
    branches: main

jobs:
  deploy:
    name: deploy-api
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "garug-bingo"
          entrypoint: "main.ts"
          root: "./api"
